package com.tcs.cma.apis.tools.constant;

/**
 * 
 * @author Manish Srivastava
 * 18 Sep 2019
 */
public interface ApiConstants {
	/**
	 * Constants used in API model
	 */
	String XML_PRE_PROCESSOR = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n";
	String ONE_TAB  = "\t";
	String TWO_TABS  = "\t\t";
	String THREE_TABS  = "\t\t\t";
	String FOUR_TABS  = "\t\t\t\t";
	String FIVE_TABS  = "\t\t\t\t\t";
	String NEW_LINE = "\n";
	String TOOL_COMMENT = "<!--This file is generated by API Proxy Generator Tool-->\n";
	String API_FLOW_TAG = "\t\t</Flow>\n";
	String API_RESPONSE_TAG = "\t\t\t<Response/>\n";
	String XML_CLOSING_TAG = "\">\n";
	String ROUTE_RULE = "RouteRule";
	String API_PARAMETER_NAME = "Parameter</Name>";
	String API_START_STEP = "<Step>";
	String API_END_STEP = "</Step>";
	String API_CONDITION_START = "<Condition>";
	String API_CONDITION_END = "</Condition>";
	String API_REQUEST_PRE_FLOW = "<Request>#PRE_FLOW_REQUEST#</Request>";
	String API_REQUEST_POST_FLOW = "<Request>#POST_FLOW_REQUEST#</Request>";
	String API_RESPONSE_PRE_FLOW = "<Response>#PRE_FLOW_RESPONSE#</Response>";
	String API_RESPONSE_POST_FLOW = "<Response>#POST_FLOW_RESPONSE#</Response>";
	String API_DEFAULT_PROXY_END_POINT = "<ProxyEndPoint>default</ProxyEndPoint>";
	String API_DEFAULT_TARGET_END_POINT = "<TargetEndpoint>default</TargetEndpoint>";
	String API_QUERY_PARAMETER = "query";
	String API_REQUEST_QUERY_PARAMETER = "(request.queryparam.";
	String API_DEFAULT_FLOW_DESCRIPTION = "Please add flow description.";
	String API_PROXY_DEFAULT_FAULT_RULE = "#common_policy_DFR#";
	String API_PROXY_REQUEST_PRE_FLOW = "#common_policy_PreFlowReq#";
	String API_PROXY_REQUEST_POST_FLOW = "#common_policy_PostFlowReq#";
	String API_PROXY_RESPONSE_PRE_FLOW = "#common_policy_PreFlowRes#";
	String API_PROXY_RESPONSE_POST_FLOW = "#common_policy_PostFlowRes#";
	String API_TARGET_REQUEST_PRE_FLOW = "#common_policy_TargetPreFlowReq#";
	String API_TARGET_REQUEST_POST_FLOW = "#common_policy_TargetPostFlowReq#";
	String API_TARGET_RESPONSE_PRE_FLOW = "#common_policy_TargetPreFlowRes#";
	String API_TARGET_RESPONSE_POST_FLOW = "#common_policy_TargetPostFlowRes#";
	String API_PROXY_UNKNOWN_RESOURCE = "#common_policy_unknown_resource#";
	String API_PROXY_VHOSTS = "#common_policy_Vhosts#";
	String API_PROXY_POST_CLIENT_FLOW_RESPONSE = "#common_policy_PostClientFlowRes#";
	String API_PROXY = "apiproxy";
	String API_POLICIES = "policies";
	String API_PROXIES = "proxies";
	String API_TARGETS = "targets";
	String API_RESOURCES = "resources";
	
	
}
